### ISSUE TITLE
rake should (probably?) be installed

### ISSUE THREAD

**Issue by programmerq** [xhost-cookbooks/openvpn#23]
The README points out that you can use the rake tasks defined in /etc/openvpn/easy-rsa/Rakefile, but rake is not available by default on an ubuntu 12.04 LTS system (and probably others).

It would be nice to be able to use the openvpn::default recipe, and be able to create users using this raketask without having to bring another recipe to install rake, or install it manually.

**Comment by jtimberman** [comment]
Finally able to review and address issues/PR's on this cookbook. 

Per #42, I think we should use `openssl_x509` resource from the [openssl cookbook](https://supermarket.chef.io/cookbooks/openssl), rather than use the Rake tasks. At the time that this cookbook was written, rake *was* installed by default on systems that had Chef at the OS level because we used OS Ruby packages and at times had a dependency on rake. Nowadays, rake is also installed by default because it is in the Chef omnibus package, as `/opt/chef/embedded/bin/rake`.
